### PR TITLE
Add support for Simplified Chinese

### PR DESCRIPTION
**Pull request by louyihua**
zh_CN should be added here.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @louyihua! I've created [OSPR-912](https://openedx.atlassian.net/browse/OSPR-912) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   added yourself to the [AUTHORS](https://github.com/edx/notifier/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@louyihua I think more actually probably needs to be done here ,to actually pull in the translations for notifier. Do you know how to do that?

**Comment by sarina** [comment]
@louyihua we should be pulling in the following languages:

ar, es_419, he, hi, pt_BR, ru, zh_CN

Can you update your PR to include all of these? And if you know how to pull the updated languages, can you let me know?

**Comment by sarina** [comment]
@louyihua you can see https://github.com/edx/notifier#internationalization-and-localization for instructions on how to pull languages down.

Please at least do this for `zh_CN`.

**Comment by louyihua** [comment]
@sarina I've included all the above language files from transifex.

**Comment by sarina** [comment]
@louyihua Looking at the translations, I think there may be some good follow up work in spending some time properly internationalizing the strings (eg the `", and"` string is worrysome). but this is a really great start, thank you so much for doing this.

**Pull request merged**
