### PR TITLE
Fixed Image in discussion digest emails.

### PR DESCRIPTION
**Pull request by attiyaIshaque**
## [TNL-4653](https://openedx.atlassian.net/browse/TNL-4653)

Fixed the broken image of email digest from the discussion forums.

### Reviewers
- [x] @Shrhawk 
- [x] @tobz

### CODE REVIEW

**Comment by awaisdar001** [comment]
@attiyaIshaque  Can you please also tag the person who renamed the image?

**Comment by Shrhawk** [comment]
+1

**Comment by Shrhawk** [comment]
👍

**Comment by attiyaIshaque** [comment]
@tobz ??

**Comment by tobz** [comment]
👍

**Comment by jibsheet** [comment]
This URL is overridden in at least two places.
https://github.com/edx/configuration/blob/master/playbooks/roles/notifier/defaults/main.yml#L54
and again in the secure overrides to
"{{ NOTIFIER_LMS_URL_BASE }}/static/images/edx-theme/edx-header-logo.png"

I would argue that making the default in this settings.py file be super specific to an edX logo is wrong and should be reverted.  I will update this URL in the secure files and redeploy the stage notifier.

**Comment by attiyaIshaque** [comment]
@jibsheet Thanks 😃

**Pull request merged**
