### PR TITLE
Use user's preferred language for notifications

### PR DESCRIPTION
**Pull request by gwprice**
@jimabramson

### CODE REVIEW

**Comment by sarina** [comment]
@jimabramson do you have any idea how Greg pulled these translations? There's no tooling in the repo and I can't find anything specific. No one has updated the translations since this PR, and there've been 3 new supported languages (as well as completed translations for French) since this PR.

**Comment by jimabramson** [comment]
@sarina I'm afraid I don't have any knowledge of that, sorry.

**Comment by gwprice** [comment]
IIRC, I just used the Transifex client as described in the README: https://github.com/edx/notifier#internationalization-and-localization

**Comment by sarina** [comment]
I nominate @gwprice for the edX True Hero award

thanks greg!!!!!

**Pull request merged**
